### ISSUE TITLE
slack_link 함수 수정 제안

### ISSUE THREAD

**Issue by channss** [wanteddev/wanted_jira_bolt#2]
slack_link 함수에서 잠재적인 문제가 보입니다.
```python
def slack_link(self, ts):
    return f'https://{SlackCollection.workspace}/archives/{self.item_channel}/p{ts.replace(".", "")}'
```
위 양식은 슬랙 채널의 **최상위 메세지에 이모지를 눌렀을 경우**만 적용되는 형태입니다.
jira bolt의 정확한 의도는 그게 맞지만 사용하는 사람들은 thread 안의 글에도 이모지를 누를 것이 분명합니다.
그럴 경우 링크 생성에 사용되는 event timestamp가 달라 전혀 관련없는 link가 생성될 수 있습니다.

더 알맞은 형태는 아래와 같습니다.
```https://{SlackCollection.workspace}/archives/{self.item_channel}/p{ts.replace(".", "")}?thread_ts={thread_ts}'```

**Comment by jongwony** [comment]
제보 감사합니다. 하지만 thread_ts 는 아무런 conversation 이 없는 경우에 thread_ts가 없는 경우도 있을거 같아요.
해당 케이스 나누어서 코드를 수정해 보도록 하겠습니다.
